import type { ReactNode } from 'react';
import {
  AccuracyIcon,
  ArrowIcon,
  BagIcon,
  BarbedVineIcon,
  BlazeIcon,
  BlessingIcon,
  BlindIcon,
  BranchIcon,
  BurnIcon,
  CardFaceIcon,
  ChiIcon,
  CleanseIcon,
  ConcussionIcon,
  CritIcon,
  DaggerIcon,
  DelayedPoisonIcon,
  DryadIcon,
  EntangleIcon,
  EvasiveIcon,
  FierySoulIcon,
  FireMasteryIcon,
  FistIcon,
  FlameIcon,
  FootIcon,
  HelmetIcon,
  KnockdownIcon,
  LeafIcon,
  LifeIcon,
  LotusIcon,
  MaskIcon,
  MeteorIcon,
  MoonIcon,
  NinjatoIcon,
  NinjutsuIcon,
  PalmIcon,
  PoisonIcon,
  PowIcon,
  PrayerIcon,
  ProtectIcon,
  RetributionIcon,
  SaplingIcon,
  SeedlingIcon,
  ShadowIcon,
  ShadowsIcon,
  ShurikenIcon,
  SmokeBombIcon,
  SneakAttackIcon,
  SpiritIcon,
  StunIcon,
  SwordIcon,
  TargetedIcon,
  WellspringIcon,
  ZenIcon,
} from './icons';

/**
 * Die symbols by id, used wherever a requirement is rendered as a row of
 * slots. Heroes that introduce a new symbol add it here.
 */
export const SYMBOL_ICONS: Record<string, () => ReactNode> = {
  sword: SwordIcon,
  helmet: HelmetIcon,
  life: LifeIcon,
  prayer: PrayerIcon,
  pow: PowIcon,
  fist: FistIcon,
  palm: PalmIcon,
  zen: ZenIcon,
  lotus: LotusIcon,
  arrow: ArrowIcon,
  foot: FootIcon,
  moon: MoonIcon,
  flame: FlameIcon,
  blaze: BlazeIcon,
  fierySoul: FierySoulIcon,
  meteor: MeteorIcon,
  dagger: DaggerIcon,
  bag: BagIcon,
  card: CardFaceIcon,
  shadow: ShadowIcon,
  ninjato: NinjatoIcon,
  shuriken: ShurikenIcon,
  mask: MaskIcon,
  branch: BranchIcon,
  leaf: LeafIcon,
  spirit: SpiritIcon,
};

/** Status effect tokens by id. */
export const STATUS_ICONS: Record<string, () => ReactNode> = {
  crit: CritIcon,
  protect: ProtectIcon,
  accuracy: AccuracyIcon,
  retribution: RetributionIcon,
  'blessing-of-divinity': BlessingIcon,
  stun: StunIcon,
  concussion: ConcussionIcon,
  chi: ChiIcon,
  evasive: EvasiveIcon,
  knockdown: KnockdownIcon,
  cleanse: CleanseIcon,
  blind: BlindIcon,
  entangle: EntangleIcon,
  targeted: TargetedIcon,
  burn: BurnIcon,
  'fire-mastery': FireMasteryIcon,
  shadows: ShadowsIcon,
  'sneak-attack': SneakAttackIcon,
  poison: PoisonIcon,
  'delayed-poison': DelayedPoisonIcon,
  'smoke-bomb': SmokeBombIcon,
  ninjutsu: NinjutsuIcon,
  seedling: SeedlingIcon,
  sapling: SaplingIcon,
  dryad: DryadIcon,
  'barbed-vine': BarbedVineIcon,
  wellspring: WellspringIcon,
};
